# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: NexGen 7T
    url: /
    weight: 10
  - name: U24
    url: u24/
    weight: 20
  - name: Workshop
    url: workshop/
    weight: 30
  #- name: Showcase
  #  url: showcase/
  #  weight: 40
  #- name: Apply
  #  url: apply/
  #  weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
